CREATE TABLE OPERACIONES(
    ID NUMERIC,
    NUMERO1 VARCHAR(50),
    NUMERO2 VARCHAR(50),
    OPERACION VARCHAR (50)
    RESULTADO VARCHAR (100),
    FECHA DATE,
    CONSTRAINT OPERACIONES_PK PRIMARY KEY (ID)
);